version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: ["poetry", "run", "gunicorn", "myproject.wsgi:application", "--workers", "3", "--bind", "0.0.0.0:8000"]
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    restart: always  # Рекомендуется добавить для автоматического перезапуска
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    restart: always  # То же самое для Redis

  worker:
    build:
      context: .
    command: ["poetry", "run", "celery", "-A", "celery_app.app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  flower:
    build:
      context: .
    command: ["poetry", "run", "celery", "-A", "celery_app.app", "flower"]
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  db_data:
